import os
from dotenv import load_dotenv

load_dotenv()

PORT = os.getenv("PORT")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")

PGUSER = os.getenv("PGUSER")
PGHOST = os.getenv("PGHOST")
PGPASSWORD = os.getenv("PGPASSWORD")
PGDATABASE = os.getenv("PGDATABASE")
PGPORT = os.getenv("PGPORT")

EMBED_MODEL_NAME = os.getenv("EMBED_MODEL_NAME")
PREFIX_DIR_MODEL = os.getenv("PREFIX_DIR_MODEL")
TEXT_GENERATION_MODEL = os.getenv("TEXT_GENERATION_MODEL")

DOCUMENT_PATH = os.getenv("DOCUMENT_PATH")
BASE_KNOWLEDGE_DOCUMENT_DIR = os.getenv("BASE_KNOWLEDGE_DOCUMENT_DIR")
BASE_KNOWLEDGE_DOCUMENT_NAME = os.getenv("BASE_KNOWLEDGE_DOCUMENT_NAME")

EMBED_MODEL_PATH = f"{PREFIX_DIR_MODEL}/{EMBED_MODEL_NAME}"
BASE_KNOWLEDGE_DOCUMENT_PATH = f"{DOCUMENT_PATH}/{BASE_KNOWLEDGE_DOCUMENT_DIR}"

DB_URI = f"postgresql://{PGUSER}:{PGPASSWORD}@{PGHOST}:{PGPORT}/{PGDATABASE}"
DB_URI_TEST = f"postgresql://{PGUSER}:{PGPASSWORD}@{PGHOST}:{int(PGPORT)+1}/{PGDATABASE}"

print(f"========= CONFIG {EMBED_MODEL_PATH} =========")
print(f"========= CONFIG {TEXT_GENERATION_MODEL} =========")
