import os
from dotenv import load_dotenv

load_dotenv()

PORT = os.getenv("PORT")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")

PGUSER = os.getenv("PGUSER")
PGHOST = os.getenv("PGHOST")
PGPASSWORD = os.getenv("PGPASSWORD")
PGDATABASE = os.getenv("PGDATABASE")
PGPORT = os.getenv("PGPORT")

EMBED_MODEL_PATH = os.getenv("EMBED_MODEL_PATH")
TEXT_GENERATION_MODEL_PATH = os.getenv("TEXT_GENERATION_MODEL_PATH")
DOCUMENT_PATH = os.getenv("DOCUMENT_PATH")
BASE_KNOWLEDGE_DOCUMENT_PATH = os.getenv("BASE_KNOWLEDGE_DOCUMENT_PATH")
BASE_KNOWLEDGE_DOCUMENT_NAME = os.getenv("BASE_KNOWLEDGE_DOCUMENT_NAME")

DB_URI = f"postgresql://{PGUSER}:{PGPASSWORD}@{PGHOST}:{PGPORT}/{PGDATABASE}"
DB_URI_TEST = f"postgresql://{PGUSER}:{PGPASSWORD}@{PGHOST}:{int(PGPORT)+1}/{PGDATABASE}"