"""file_name and custom_name

Revision ID: 5ebff3fdde73
Revises: cae16e15ef23
Create Date: 2024-05-23 16:29:19.207313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebff3fdde73'
down_revision: Union[str, None] = 'cae16e15ef23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('custom_name', sa.String(length=100), nullable=False))
    op.add_column('files', sa.Column('file_name', sa.String(length=100), nullable=False))
    op.drop_constraint('files_name_key', 'files', type_='unique')
    op.create_unique_constraint(None, 'files', ['custom_name'])
    op.drop_column('files', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='unique')
    op.create_unique_constraint('files_name_key', 'files', ['name'])
    op.drop_column('files', 'file_name')
    op.drop_column('files', 'custom_name')
    # ### end Alembic commands ###
