version: "1.0"

services:
  postgres-test:
    container_name: postgres_chatbot_test
    image: postgres:9.6
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
