version: "1.0"

services:
  postgres:
    container_name: postgres_chatbot
    image: postgres:9.6
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    volumes:
      - postgres-chatbot:/var/lib/postgresql/data

volumes:
  postgres-chatbot:
